# https://nixpacks.com/docs/configuration/file

# set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update notification is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is also pretty useless in a production environment

# install caddy
[phases.caddy]
    nixpkgsArchive = '727db88c063586d2f912af26dc3ce19d6f31af05' # Caddy 2.7.6 https://github.com/NixOS/nixpkgs/commit/727db88c063586d2f912af26dc3ce19d6f31af05
    nixPkgs = ['caddy'] # install caddy from nix packages

# format the Caddyfile with fmt
[phases.fmt]
    dependsOn = ['caddy'] # make sure this phase runs after the 'caddy' phase so that we know we have caddy downloaded
    cmds = ['caddy fmt --overwrite ./apps/frontend/Caddyfile'] # format the Caddyfile to fix any formatting inconsistencies